# This is a basic workflow to help you get started with Actions
              
- name: Eleventy Action
  uses: TartanLlama/actions-eleventy@v1.3
  with:
    args: --output _dist
    install_dependencies: true
